package domain;
// Generated 25-Dec-2021 21:04:15 by Hibernate Tools 4.3.1


import java.util.Date;


/**
 * Appointment generated by hbm2java
 */
public class Appointment  implements java.io.Serializable {


     private Integer id;
     private String patient;
     private Date date;

    public Appointment() {
    }

    public Appointment(String patient, Date date) {
       this.patient = patient;
       this.date = date;
    }

    public Appointment(Integer id, String patient, Date date) {
        this.id = id;
        this.patient = patient;
        this.date = date;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getPatient() {
        return this.patient;
    }
    
    public void setPatient(String patient) {
        this.patient = patient;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


